import type { AppStore } from '../types';

export const seedData: AppStore = {
  settings: {
    organizationName: 'Faraj Fund',
    workStartTime: '07:30',
    workEndTime: '15:30',
    weekdayEndTime: '15:30',
    fridayEndTime: '12:00',
    gracePeriodMinutes: 0,
    defaultMonthlyPermissionBalance: 4,
    lateThresholdTime: '08:00',
    lateBaselineBeforeChange: '08:00',
    lateBaselineAfterChange: '07:30',
    lateBaselineChangeDate: '2026-05-12',
    ptMonthlyAllowanceMinutes: 240,
    ptPermissionRequiredFromDate: '2026-05-12',
    annualLeaveDays: 30,
    maternityLeaveDays: 60,
    paternityLeaveDays: 5,
    hajjLeaveDays: 30,
    compassionateLeaveDays: 3,
    consecutiveAbsenceWarning: 5,
    consecutiveAbsenceTermination: 14,
    nonConsecutiveAbsenceTermination: 30,
    departments: ['HR', 'Finance', 'Operations', 'IT', 'Admin', 'Logistics', 'Support Services'],
    categories: ['Main Employee', 'Support Staff'],
    supportStaffDisciplinaryEnabled: false,
    anthropicApiKey: '',
  },

  employees: [
    { id: 'e1',  employeeCode: '1',  employeeName: 'Meherzia Dallali',  employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Staff',        group: 'B',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e2',  employeeCode: '2',  employeeName: 'Muhammad Hussein',  employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Staff',        group: 'B',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e3',  employeeCode: '3',  employeeName: 'Abdalla ADIB',      employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Staff',        group: 'A',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e4',  employeeCode: '4',  employeeName: 'Obaid Sultan',      employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Staff',        group: 'A',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e5',  employeeCode: '5',  employeeName: 'Hasan ElHag',       employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Staff',        group: 'A',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e6',  employeeCode: '6',  employeeName: 'Naeem AlShami',     employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Staff',        group: 'A',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e7',  employeeCode: '7',  employeeName: 'Obaid Al Nuaimi',   employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Staff',        group: 'A',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e8',  employeeCode: '8',  employeeName: 'Haytham AlNuaimi',  employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Staff',        group: 'A',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e9',  employeeCode: '10', employeeName: 'Fatin AlShehhi',    employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Staff',        group: 'A',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e10', employeeCode: '11', employeeName: 'Hamda AlKhateri',   employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Staff',        group: 'B',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e11', employeeCode: '12', employeeName: 'Nour El Khoudaimi', employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Staff',        group: 'A',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e12', employeeCode: '13', employeeName: 'Baraa Jamal',       employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Staff',        group: 'B',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e13', employeeCode: '14', employeeName: 'Faith Jacob',       employeeCategory: 'Main Employee', department: 'HR',              designation: 'HR Officer',   group: 'B',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e14', employeeCode: '16', employeeName: 'Mohamad ALHosani',  employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Staff',        group: '-',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e15', employeeCode: '17', employeeName: 'Fahad AlHammadi',   employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Staff',        group: '-',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e16', employeeCode: '18', employeeName: 'Khalid Baslaib',    employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Staff',        group: '-',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e17', employeeCode: '19', employeeName: 'Faiza Haddad',      employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Staff',        group: '-',        workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e18', employeeCode: '20', employeeName: 'Saleh AlKetbi',     employeeCategory: 'Main Employee', department: 'Admin',           designation: 'Director',     group: 'Director', workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e19', employeeCode: 'S1', employeeName: 'Summaya',           employeeCategory: 'Support Staff', department: 'Support Services', designation: 'Support Staff', group: 'Support', workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
    { id: 'e20', employeeCode: 'S2', employeeName: 'Safwan',            employeeCategory: 'Support Staff', department: 'Support Services', designation: 'Support Staff', group: 'Support', workTiming: '07:30–15:30', monthlyPermissionBalance: 4, status: 'Active', enableDisciplinary: false, notes: '' },
  ],

  uploadLogs: [],
  attendanceRecords: [],
  leaveRecords: [],
  managementDecisions: [],
  emailLogs: [],
  pendingDocuments: [],
  followUpCases: [],
  disciplinaryRecords: [],
  dailyTasks: [],
};
